export const SET_FETCHING_STATUS = "SET_FETCHING_STATUS";

export const FETCH_COLLECTIONS = "FETCH_COLLECTIONS";
export const APPEND_COLLECTIONS = "APPEND_COLLECTIONS";

export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const SET_COLLECTION = "SET_COLLECTION";
